### create client
POST http://localhost:8999/api/v1/clients/
Content-Type: application/json

{
  "fio": "Smith Jak Bin",
  "birthday": "1999-10-10",
  "phone": ["89227771234", "89033806543"],
  "email": ["cxcxcxc@gmail.com", "llll@mail.ru"],
  "login": "ooooouuuuttt",
  "password": "postgreSQL",
  "balance": 201099
}

### find by param
GET http://localhost:8999/api/v1/clients/?phone=89370001245

### add Email
GET http://localhost:8999/api/v1/clients/addEmail?clientId=1&email=eeeeee@mail.ru

### delete Email
DELETE http://localhost:8999/api/v1/clients/email/qwerty@mail.ru

### add Phone
GET http://localhost:8999/api/v1/clients/addPhone?clientId=1&phone=89033124455

### delete Phone
DELETE http://localhost:8999/api/v1/clients/phone/89033124455

### increase in Balance
PUT http://localhost:8999/api/v1/clients/

### transfer money
PUT http://localhost:8999/api/v1/clients/transfer?clientIdSender=1&clientIdRecipient=2&money=50