### create client
POST http://localhost:8999/api/v1/clients/
Content-Type: application/json

{
  "id": 7,
  "fio": "Smith Jak Bin",
  "birthday": "1999-10-10",
  "phone": ["89227771234", "89033806543"],
  "email": ["cxcxcxc@gmail.com", "llll@mail.ru"],
  "login": "ooooouuuuttt",
  "password": "postgreSQL",
  "balance": 201099
}

### find by param
GET http://localhost:8999/api/v1/clients/?phone=89370001245