### create client
POST http://localhost:8999/api/v1/clients/
Content-Type: application/json

{
  "fio": "Smith Jak Bin",
  "birthday": "1999-10-10",
  "phone": ["89997778855", "89005556611"],
  "email": ["eeeeeee@gmail.com", "ooooooooo@mail.ru"],
  "login": "zzzzzzzzzzzzzPPPPP",
  "password": "postgreSQL",
  "startBalance": 200,
  "balance": 200
}

### find by param
GET http://localhost:8999/api/v1/clients/?phone=89370001245

### add Email
POST http://localhost:8999/api/v1/emails/
Content-Type: application/json

{
  "clientId": 1,
  "email": "dfdjfsdfsk@mail.ru"
}

### delete Email
DELETE http://localhost:8999/api/v1/emails/wewrwewrw@mail.ru

### add Phone
GET http://localhost:8999/api/v1/phones/
Content-Type: application/json

{
  "clientId": 1,
  "phone": "89006664411"
}

### delete Phone
DELETE http://localhost:8999/api/v1/phones/89370008899

### increase In Balance
PUT http://localhost:8999/api/v1/clients/

### transfer
PUT http://localhost:8999/api/v1/clients/transfer?clientIdSender=1&clientIdRecipient=2&money=10