spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: eSeNia300721
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
server:
  port: 8999